<?php
declare(strict_types=1);

// PhoneNumberValidator SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

PhoneNumberValidatorUtility::setRegistrar(function (PhoneNumberValidatorUtility $u): void {
    $u->clean = [PhoneNumberValidatorClean::class, 'call'];
    $u->done = [PhoneNumberValidatorDone::class, 'call'];
    $u->make_error = [PhoneNumberValidatorMakeError::class, 'call'];
    $u->feature_add = [PhoneNumberValidatorFeatureAdd::class, 'call'];
    $u->feature_hook = [PhoneNumberValidatorFeatureHook::class, 'call'];
    $u->feature_init = [PhoneNumberValidatorFeatureInit::class, 'call'];
    $u->fetcher = [PhoneNumberValidatorFetcher::class, 'call'];
    $u->make_fetch_def = [PhoneNumberValidatorMakeFetchDef::class, 'call'];
    $u->make_context = [PhoneNumberValidatorMakeContext::class, 'call'];
    $u->make_options = [PhoneNumberValidatorMakeOptions::class, 'call'];
    $u->make_request = [PhoneNumberValidatorMakeRequest::class, 'call'];
    $u->make_response = [PhoneNumberValidatorMakeResponse::class, 'call'];
    $u->make_result = [PhoneNumberValidatorMakeResult::class, 'call'];
    $u->make_point = [PhoneNumberValidatorMakePoint::class, 'call'];
    $u->make_spec = [PhoneNumberValidatorMakeSpec::class, 'call'];
    $u->make_url = [PhoneNumberValidatorMakeUrl::class, 'call'];
    $u->param = [PhoneNumberValidatorParam::class, 'call'];
    $u->prepare_auth = [PhoneNumberValidatorPrepareAuth::class, 'call'];
    $u->prepare_body = [PhoneNumberValidatorPrepareBody::class, 'call'];
    $u->prepare_headers = [PhoneNumberValidatorPrepareHeaders::class, 'call'];
    $u->prepare_method = [PhoneNumberValidatorPrepareMethod::class, 'call'];
    $u->prepare_params = [PhoneNumberValidatorPrepareParams::class, 'call'];
    $u->prepare_path = [PhoneNumberValidatorPreparePath::class, 'call'];
    $u->prepare_query = [PhoneNumberValidatorPrepareQuery::class, 'call'];
    $u->graphql_body = [PhoneNumberValidatorGraphql::class, 'body'];
    $u->graphql_errors = [PhoneNumberValidatorGraphql::class, 'errors'];
    $u->result_basic = [PhoneNumberValidatorResultBasic::class, 'call'];
    $u->result_body = [PhoneNumberValidatorResultBody::class, 'call'];
    $u->result_headers = [PhoneNumberValidatorResultHeaders::class, 'call'];
    $u->transform_request = [PhoneNumberValidatorTransformRequest::class, 'call'];
    $u->transform_response = [PhoneNumberValidatorTransformResponse::class, 'call'];
});
